titles with the same name but unique ids are chosen from taxonomy
DBCDK/content-first pull request #1352
Opened 2021-03-18 10:31 UTC by stanvins

based on category to which they are associated

2021-03-18 14:10 UTC, kfudbc requested changes

2021-03-18 14:10 UTC, kfudbc commented on src/client/utils/booksTaxonomy.js
> +    for (let prop in fromTitleMap) {
Problemet ved denne måde at løbe alle tags igennem på, kan være performance. Før lavede den et enkelt opslag i mappet, nu løber den alle tags igennem og tjekker parents. Jeg ville have det bedre med noget der tager konstant tid - da det her er en funktion der bliver kaldt mange gange.
Men det kræver så at vi skal generere en ny map struktur, så du kan lave følgende opslag:
taxonomy["handler om"]["some-title"]

2021-03-19 12:28 UTC, stanvins commented on src/client/utils/booksTaxonomy.js
> +    for (let prop in fromTitleMap) {
👍🏻

2021-03-19 12:44 UTC, kfudbc approved these changes
Det var da en smart måde at gøre det på :+1:

2021-03-19 12:56 UTC, merged